import { Component, ViewContainerRef, ComponentFactoryResolver } from '@angular/core';
import { SwPush } from '@angular/service-worker';
import { MatSnackBar } from '@angular/material/snack-bar';
import { Router, NavigationEnd, Event, NavigationStart, NavigationCancel, NavigationError, ActivatedRoute } from '@angular/router';
import { filter, map, first } from 'rxjs/operators';
import { Subscription } from 'rxjs';
import { MapserviceService } from '@map/mapservice.service';
import { MaterialFirebaseService } from '@material-firebase/material-firebase.service';

declare var gtag;
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  subscription: Subscription;
  public isWaiting: boolean;
  message: string ='';
  public name: string;
  fireData = [];
  newData = [];
  mainKeys = [];

  constructor(private mapService: MapserviceService, private router: Router,
              private route: ActivatedRoute,
              private snackbar: MatSnackBar, private swPush: SwPush,
              private viewContainerRef: ViewContainerRef,
              private cfr: ComponentFactoryResolver,
              private fService: MaterialFirebaseService) {
    // Google Analytics ... 
    const navEndEvents = this.router.events.pipe(
      filter (events =>  events instanceof NavigationEnd),
    );

    navEndEvents.subscribe( (event: NavigationEnd ) => {
      gtag('config', 'UA-143173960-1' , {
        // this gtag is generated by Google Ananlytics refere index.html file..
        'page_path': event.urlAfterRedirects
      } );
    } );
  }

  objectKeys(data){
    //console.log(data);
    this.newData = [];
    data.map(element => {
      Object.keys(element).forEach( keys => keys !== '$key' ? this.newData.push(element[keys]) : '' )
      
    });
  }
  detail(row, i){
    console.log(this.fireData)
    let keys = [];
    
    Object.keys (this.fireData[0][i]).forEach(key => key !== '$key' ? keys.push ( {subKeys: key}) : 
      keys.push({mainKey : this.fireData[0][i]['$key'] })  )
  console.log(...keys)
  this.mainKeys.push(...keys)
 

    //console.log(row, i)
    //console.log(this.fireData[0][i])
    //this.fireData.forEach(val => console.log('data ', val))
    //Object.keys(tmp[i]).forEach(val => console.log(val));
  }
  ngOnInit() {

        this.fService.a.list('/orders').  snapshotChanges().pipe(
           map(action => action.map(a => ({$key: a.key, ...a.payload.val() as object })))
          ).subscribe(val =>  { 
            this.fireData = [];
            this.fireData.push (val)
            console.log(this.fireData)
            this.objectKeys(val);
          })
   // navigator.serviceWorker.register('/Angular-Demo/ngsw-worker.js');
     
        this.router.events.subscribe(   (event: Event) => {
            this.checkEvent(event);
      });
        this.subscription = this.mapService.getCurrentLocation().subscribe(location => {
        /*  this.snackbar.open(location.currentLat + ' and ' + location.currentLng, '', {
          duration: 3000
        }); */
      }, err => { this.snackbar.open(err, '', {duration: 3000})},
         () => console.log('locatoin received')
      );
  }
  async onLoadLazy(){
    this.viewContainerRef.clear();
    const {LazyCmpComponent} = await import ('./lazy-cmp.component');
    this.viewContainerRef.createComponent(
      this.cfr.resolveComponentFactory(LazyCmpComponent)
    )
  }
  onActivate(componentReference) {
    this.name = componentReference.title;
  }
  // loading spinner for Lazy loading mudle..
  checkEvent(event: Event) {
    if (event instanceof NavigationStart) {
      this.isWaiting = true;
    }
    if (event instanceof NavigationEnd || event instanceof NavigationCancel || event instanceof NavigationError) {
      this.isWaiting = false;
    }
  }
  ngOnDestroy() {
    this.subscription.unsubscribe();
  }
}
