import { Component } from '@angular/core';
import { SwUpdate, SwPush } from '@angular/service-worker';
import { MatSnackBar } from '@angular/material';
import { Router, NavigationEnd, Event, NavigationStart, NavigationCancel, NavigationError, ActivatedRoute } from '@angular/router';
import { filter } from 'rxjs/operators';
import { Navigation } from 'selenium-webdriver';

declare var gtag;
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  public isWaiting: boolean;
  message: string ='';
  public name: string;
  constructor( private router: Router, private route: ActivatedRoute ) {
    // Google Analytics ... 
    const navEndEvents = this.router.events.pipe(
      filter (events =>  events instanceof NavigationEnd),

    );

    this.router.events.subscribe(   (event: Event) =>{
      this.checkEvent(event);
    } );
    
    navEndEvents.subscribe( (event: NavigationEnd ) => {
      gtag('config', 'UA-143173960-1' , {
        // this gtag is generated by Google Ananlytics refere index.html file..
        'page_path': event.urlAfterRedirects
      } );
    } );
  }
  checkEvent(event: Event){
    if (event instanceof NavigationStart){
      this.isWaiting = true;
      
    }
    if(event instanceof NavigationEnd || event instanceof NavigationCancel || event instanceof NavigationError){
      this.isWaiting = false;
    }
  }
  ngOnInit() {
   // navigator.serviceWorker.register('/Angular-Demo/ngsw-worker.js');
    
  }
  onActivate(componentReference) {
    this.name = componentReference.title;
  }
}
